more fixes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,6 +22,10 @@ jobs:
       with:
         python-version: "3.10"
 
+    - name: Clean previous builds
+      run: |
+        rm -rf dist
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -30,34 +34,54 @@ jobs:
 
     - name: Build executable
       run: |
-        if [ "${{ matrix.os }}" == "windows-latest" ]; then \
-          pyinstaller --onefile --name MdnsBroadcaster --distpath dist/windows --add-data "iplist.txt;." src/Main.py \
-          if [ ! -f dist/windows/MdnsBroadcaster.exe ]; then \
-            echo "Build failed: dist/windows/MdnsBroadcaster.exe not found"; \
-            exit 1; \
-          fi; \
-        else \
-          pyinstaller --onefile --name MdnsBroadcaster --distpath dist/linux --add-data "iplist.txt;." src/Main.py \
-          if [ ! -f dist/linux/MdnsBroadcaster ]; then \
-            echo "Build failed: dist/linux/MdnsBroadcaster not found"; \
-            exit 1; \
-          fi; \
+        if [ "${{ matrix.os }}" == "windows-latest" ]; then
+          pyinstaller --onefile --name MdnsBroadcaster --distpath dist/windows --add-data "iplist.txt;." src/Main.py
+          if [ ! -f dist/windows/MdnsBroadcaster.exe ]; then
+            echo "Build failed: dist/windows/MdnsBroadcaster.exe not created"
+            exit 1
+          fi
+        else
+          pyinstaller --onefile --name MdnsBroadcaster --distpath dist/linux --add-data "iplist.txt:." src/Main.py
+          if [ ! -f dist/linux/MdnsBroadcaster ]; then
+            echo "Build failed: dist/linux/MdnsBroadcaster not created"
+            exit 1
+          fi
         fi
       shell: bash
+
+    - name: Upload artifact
+      uses: actions/upload-artifact@v3
+      with:
+        name: ${{ matrix.os }}-executable
+        path: |
+          dist/windows/MdnsBroadcaster.exe
+          dist/linux/MdnsBroadcaster
 
   release:
     needs: build
     runs-on: ubuntu-latest
+    env:
+      VERSION: v1.0.2 # Define the version here
     steps:
     - name: Checkout code
       uses: actions/checkout@v4
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v3
+
+    - name: Create and Push Git Tag
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        git tag $VERSION
+        git push origin $VERSION
 
     - name: Create GitHub Release
       id: create_release
       uses: actions/create-release@v1
       with:
-        tag_name: v1.0.2
-        release_name: "Release v1.0.2"
+        tag_name: ${{ env.VERSION }}
+        release_name: "Release ${{ env.VERSION }}"
         body: |
           This release includes the following executables:
           - Windows executable
